version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb:10.3
        ports: 
            - "3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf/my.cnf:/etc/my.cnf
            - persistent:/home/retya/files/docker/conferenceMapper/mysl
        networks:
            - default
volumes:
   persistent:
